apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLables:
      app: python
  replicas: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: flask-app
          image: ashishkadian/flask-app:v1
          ports:
            - containerPort: 8000



---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: python
    ports:
      - protocol: TCP
        port: 8000
        targetPort: 8000
    type: NodePort
