apiVersion: v1
kind: Deployment
metadata: 
  name: db
spec:
  replicas: 1
  template:
    image: mysql
  port:
    3306


---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports: 
    3306:3306
  type: ClusterIp

  
